apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nqu6ko61k-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:e577ef2d40ef91c3c4a8cdee410d09dc2c3058cb@sha256:3e0cc16028b7fcdbb3dc6f98d4503555e8d239a6550ea72404f983098d230c91
          name: container-image
