apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nqu6ko61k-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nqu6ko61k-nodejs 
  name: nqu6ko61k-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nqu6ko61k-nodejs 
